use crate::{
    ast::WktNode,
    base_types::{
        AngleUnit, AreaDescription, Citation, GeographicBoundingBox, Id, LengthUnit,
        ParametricUnit, PrimeMeridian, Remark, ScaleUnit, Scope, TemporalExtent, TimeUnit,
        VerticalExtent,
    },
    error::WktParseError,
};

pub struct WktResult<T: WktBaseType + Sized> {
    pub result: T,
    pub consumed: usize,
}

pub trait WktBaseType
where
    Self: Sized,
{
    fn from_nodes<'a, I>(wkt_nodes: I) -> Result<WktResult<Self>, WktParseError>
    where
        I: IntoIterator<Item = &'a WktNode>;
}

pub enum WktCrsTypes {
    Scope(Scope),
    Extent(Extent),
    AreaDescription(AreaDescription),
    GeographicBoundingBox(GeographicBoundingBox),
    VerticalExtent(VerticalExtent),
    TemporalExtent(TemporalExtent),
    Identifier(Id),
    Citation(Citation),
    Remark(Remark),
    LengthUnit(LengthUnit),
    ParametricUnit(ParametricUnit),
    ScaleUnit(ScaleUnit),
    TimeUnit(TimeUnit),
    AngleUnit(AngleUnit),
    CoordinateSystem(CoordinateSystem),
    Meridian(Meridian),
    Bearing(Bearing),
    Order(Order),
    GeodeticDatumEnsemble(GeodeticDatumEnsemble),
    VerticalDatumEnsemble(VerticalDatumEnsemble),
    DatumEnsembleMember(DatumEnsembleMember),
    DatumEnsembleAccuracy(DatumEnsembleAccuracy),
    DynamicCrs(DynamicCrs),
    FrameEpoch(FrameEpoch),
    DeformationModelId(DeformationModelId),
    GeodeticCrs(GeodeticCrs),
    GeographicCrs(GeographicCrs),
    Ellipsoid(Ellipsoid),
    PrimeMeridian(PrimeMeridian),
    GeodeticReferenceFrame(GeodeticReferenceFrame),
    ProjectedCrs(ProjectedCrs),
    BaseGeodeticCrs(BaseGeodeticCrs),
    BaseGeographicCrs(BaseGeographicCrs),
    MapProjection(MapProjection),
    MapProjectionMethod(MapProjectionMethod),
    MapProjectionParameter(MapProjectionParameter),
    VerticalCrs(VerticalCrs),
    GeoidModel(GeoidModel),
    VerticalReferenceFrame(VerticalReferenceFrame),
    DatumAnchor(DatumAnchor),
    EngineeringCrs(EngineeringCrs),
    EngineeringDatum(EngineeringDatum),
    ParametricCrs(ParametricCrs),
    ParametricDatum(ParametricDatum),
    TimeCrs(TimeCrs),
    TemporalDatum(TemporalDatum),
    TimeOrigin(TimeOrigin),
    Calendar(Calendar),
    DerivingConversion(DerivingConversion),
    DerivedCrsConversionMethod(DerivedCrsConversionMethod),
    DerivedCrsConversionParameter(DerivedCrsConversionParameter),
    DerivedCrsConversionParameterFile(DerivedCrsConversionParameterFile),
    DerivedProjectedCrs(DerivedProjectedCrs),
    BaseProjectedCrs(BaseProjectedCrs),
    DerivedVerticalCrs(DerivedVerticalCrs),
    BaseVerticalCrs(BaseVerticalCrs),
    DerivedEngineeringCrs(DerivedEngineeringCrs),
    BaseEngineeringCrs(BaseEngineeringCrs),
    DerivedParametricCrs(DerivedParametricCrs),
    BaseParametricCrs(BaseParametricCrs),
    DerivedTemporalCrs(DerivedTemporalCrs),
    BaseTemporalCrs(BaseTemporalCrs),
    CompoundCrs(CompoundCrs),
    MetadataCoordinateEpoch(MetadataCoordinateEpoch),
    CoordinateMetadata(CoordinateMetadata),
    CoordinateOperation(CoordinateOperation),
    OperationVersion(OperationVersion),
    SourceCrs(SourceCrs),
    TargetCrs(TargetCrs),
    OperationMethod(OperationMethod),
    OperationParameter(OperationParameter),
    OperationParameterFile(OperationParameterFile),
    InterpolationCrs(InterpolationCrs),
    OperationAccuracy(OperationAccuracy),
    PointMotionOperation(PointMotionOperation),
    ConcatenatedOperation(ConcatenatedOperation),
    BoundCrs(BoundCrs),
    AbridgedCoordinateTransformation(AbridgedCoordinateTransformation),
}
